# Generated by Django 4.2.5 on 2023-10-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book',
            new_name='Games',
        ),
    ]
